# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          CNB_TOKEN: ${{ secrets.CNB_TOKEN }}
        run: |
          curl -LO https://download.pytorch.org/libtorch/cu124/libtorch-cxx11-abi-shared-with-deps-2.4.0%2Bcu124.zip
          sha256sum *.zip
          docker run --rm \
            -e TZ=Asia/Shanghai \
            -e CNB_TOKEN="$CNB_TOKEN" \
            -e CNB_API_ENDPOINT='https://api.cnb.cool' \
            -e CNB_REPO_SLUG='Jaime/rust-camp-s02-rust-embedded/env' \
            -e PLUGIN_TAG='libtorch' \
            -e PLUGIN_ATTACHMENTS='libtorch-cxx11-abi-shared-with-deps-2.4.0%2Bcu124.zip' \
            -v $(pwd):$(pwd) \
            -w $(pwd) \
            cnbcool/attachments:latest
